name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 139.59.244.109 >> ~/.ssh/known_hosts

    - name: Install dependencies
      run: yarn install

    - name: Build the project
      run: yarn build

    - name: Delete build folder on server
      run: |
        ssh -o StrictHostKeyChecking=no root@139.59.244.109 'bash -s' < ./scripts/delete-build-folder.sh
      shell: bash

    - name: Copy build folder to server
      run: |
        scp -r ./.next root@139.59.244.109:/var/pavloff-dev

    - name: Restart DigitalOcean Web Server
      run: |
        ssh -o StrictHostKeyChecking=no root@139.59.244.109 'bash -s' < ./scripts/restart.sh
      shell: bash